#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/lib/library.sh"

SOURCE_PATH=
OUTPUT_PATH=
REVISION=0

function usage()
{
    echo "Usage: ./build-rbenv-rpm <OPTIONS>"
    echo "Build an Rbenv RPM package."
    echo
    echo "Required options:"
    echo "  -s PATH     Path to Rbenv source tree"
    echo "  -o PATH     Path to output package file"
    echo
    echo "Optional options:"
    echo "  -r REVISION Package revision number (default: $REVISION)"
    echo "  -h          Show usage"
}

function parse_options()
{
    local OPTIND=1
    local ORIG_ARGV
    local opt
    while getopts "s:o:r:h" opt; do
        case "$opt" in
        s)
            SOURCE_PATH=$(absolute_path "$OPTARG")
            ;;
        o)
            OUTPUT_PATH=$(absolute_path "$OPTARG")
            ;;
        r)
            REVISION="$OPTARG"
            ;;
        h)
            usage
            exit
            ;;
        *)
            return 1
            ;;
        esac
    done

    (( OPTIND -= 1 )) || true
    shift $OPTIND || true
    ORIG_ARGV=("$@")

    if [[ "$SOURCE_PATH" = "" ]]; then
        echo 'ERROR: please specify an Rbenv source path with -s.' >&2
        exit 1
    fi
    if [[ ! -e "$SOURCE_PATH" ]]; then
        echo "ERROR: $SOURCE_PATH does not exist." >&2
        exit 1
    fi
    if [[ "$OUTPUT_PATH" = "" ]]; then
        echo 'ERROR: please specify an output package path with -o.' >&2
        exit 1
    fi
}

parse_options "$@"

if tty -s; then
    TTY_ARGS=(-t -i)
else
    TTY_ARGS=()
fi

IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/utility/image_tag")
OUTPUT_TEMP_PATH=$(mktemp "$OUTPUT_PATH.XXXXXX")
create_file_if_missing "$OUTPUT_TEMP_PATH"

echo '--- Entering Docker container ---'
verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
    -v "$SELFDIR:/system:ro" \
    -v "$SOURCE_PATH:/input/rbenv:ro" \
    -v "$OUTPUT_TEMP_PATH:/output/rbenv.rpm" \
    -e "REVISION=$REVISION" \
    --user "$(id -u):$(id -g)" \
    "fullstaq/ruby-build-env-utility:$IMAGE_VERSION" \
    /system/container-entrypoints/build-rbenv-rpm
EXIT_STATUS=$?
set -e
echo '--- Exited Docker container ---'
if [[ "$EXIT_STATUS" -eq 0 ]]; then
    run mv "$OUTPUT_TEMP_PATH" "$OUTPUT_PATH"
else
    run rm -f "$OUTPUT_TEMP_PATH"
fi
