#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/lib/library.sh"

BINARY_TARBALL_PATH=
OUTPUT_PATH=
REVISION=0

function usage()
{
    echo "Usage: ./build-ruby-deb <OPTIONS>"
    echo "Build a Ruby Debian package from its binary tarball (which is produced by ./build-ruby)."
    echo
    echo "Required options:"
    echo "  -b PATH     Path to Ruby binary tarball (as built by ./build-ruby)"
    echo "  -o PATH     Path to output package file"
    echo
    echo "Optional options:"
    echo "  -r REVISION Package revision number (default: $REVISION)"
    echo "  -h          Show usage"
}

function parse_options()
{
    local OPTIND=1
    local ORIG_ARGV
    local opt
    while getopts "b:o:r:h" opt; do
        case "$opt" in
        b)
            BINARY_TARBALL_PATH=$(absolute_path "$OPTARG")
            ;;
        o)
            OUTPUT_PATH=$(absolute_path "$OPTARG")
            ;;
        r)
            REVISION="$OPTARG"
            ;;
        h)
            usage
            exit
            ;;
        *)
            return 1
            ;;
        esac
    done

    (( OPTIND -= 1 )) || true
    shift $OPTIND || true
    ORIG_ARGV=("$@")

    if [[ "$BINARY_TARBALL_PATH" = "" ]]; then
        echo 'ERROR: please specify a Ruby binary tarball path with -b.' >&2
        exit 1
    fi
    if [[ ! -e "$BINARY_TARBALL_PATH" ]]; then
        echo "ERROR: $BINARY_TARBALL_PATH does not exist." >&2
        exit 1
    fi
    if [[ "$OUTPUT_PATH" = "" ]]; then
        echo 'ERROR: please specify an output package path with -o.' >&2
        exit 1
    fi
}

parse_options "$@"

if tty -s; then
    TTY_ARGS=(-t -i)
else
    TTY_ARGS=()
fi

IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/utility/image_tag")
OUTPUT_TEMP_PATH=$(mktemp "$OUTPUT_PATH.XXXXXX")
create_file_if_missing "$OUTPUT_TEMP_PATH"

echo '--- Entering Docker container ---'
verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
    -v "$SELFDIR:/system:ro" \
    -v "$BINARY_TARBALL_PATH:/input/ruby-bin.tar.gz:ro" \
    -v "$OUTPUT_TEMP_PATH:/output/ruby.deb" \
    -e "REVISION=$REVISION" \
    --user "$(id -u):$(id -g)" \
    "fullstaq/ruby-build-env-utility:$IMAGE_VERSION" \
    /system/container-entrypoints/build-ruby-deb
EXIT_STATUS=$?
set -e
echo '--- Exited Docker container ---'
if [[ "$EXIT_STATUS" -eq 0 ]]; then
    run mv "$OUTPUT_TEMP_PATH" "$OUTPUT_PATH"
else
    run rm -f "$OUTPUT_TEMP_PATH"
fi
