#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/lib/library.sh"

ENVIRONMENT_NAME=
SOURCE_PATH=
OUTPUT_PATH=
BUILD_CONCURRENCY=1
CACHE_PATH=

function usage()
{
    echo "Usage: ./build-jemalloc <OPTIONS>"
    echo "Build a Jemalloc binary tarball from its source tarball."
    echo
    echo "Required options:"
    echo "  -n NAME     Name of environment to build in (one of: $(list_environment_names "$SELFDIR/environments"))"
    echo "  -s PATH     Path to Jemalloc source tarball"
    echo "  -o PATH     Path to output tarball"
    echo
    echo "Optional options:"
    echo "  -j NUM      Build concurrency (default: $BUILD_CONCURRENCY)"
    echo "  -c PATH     Use given directory as cache"
    echo "  -h          Show usage"
}

function parse_options()
{
    local OPTIND=1
    local ORIG_ARGV
    local opt
    while getopts "n:s:o:j:c:h" opt; do
        case "$opt" in
        n)
            ENVIRONMENT_NAME="$OPTARG"
            ;;
        s)
            SOURCE_PATH=$(absolute_path "$OPTARG")
            ;;
        o)
            OUTPUT_PATH=$(absolute_path "$OPTARG")
            ;;
        j)
            BUILD_CONCURRENCY="$OPTARG"
            ;;
        c)
            CACHE_PATH=$(absolute_path "$OPTARG")
            ;;
        h)
            usage
            exit
            ;;
        *)
            return 1
            ;;
        esac
    done

    (( OPTIND -= 1 )) || true
    shift $OPTIND || true
    ORIG_ARGV=("$@")

    if [[ "$ENVIRONMENT_NAME" = "" ]]; then
        echo 'ERROR: please specify an environment name with -n.' >&2
        exit 1
    fi
    if [[ "$SOURCE_PATH" = "" ]]; then
        echo 'ERROR: please specify a Jemalloc source tarball path with -s.' >&2
        exit 1
    fi
    if [[ ! -e "$SOURCE_PATH" ]]; then
        echo "ERROR: $SOURCE_PATH does not exist." >&2
        exit 1
    fi
    if [[ "$OUTPUT_PATH" = "" ]]; then
        echo 'ERROR: please specify an output tarball path with -o.' >&2
        exit 1
    fi
    if [[ "$CACHE_PATH" != "" && ! -e "$CACHE_PATH" ]]; then
        echo "ERROR: $CACHE_PATH does not exist." >&2
        exit 1
    fi
}

parse_options "$@"

if tty -s; then
    TTY_ARGS=(-t -i)
else
    TTY_ARGS=()
fi
if [[ "$CACHE_PATH" != "" ]]; then
    CACHE_PATH_MOUNT_ARGS=(-v "$CACHE_PATH:/cache:delegated")
else
    CACHE_PATH_MOUNT_ARGS=()
fi

IMAGE_VERSION=$(read_single_value_file "$SELFDIR/environments/$ENVIRONMENT_NAME/image_tag")
OUTPUT_TEMP_PATH=$(mktemp "$OUTPUT_PATH.XXXXXX")
create_file_if_missing "$OUTPUT_TEMP_PATH"

echo '--- Entering Docker container ---'

function _cleanup() {
    echo
    echo '--- Exited Docker container ---'
    run rm -f "$OUTPUT_TEMP_PATH"
}

verbose_run docker run --rm --init "${TTY_ARGS[@]}" \
    -v "$SELFDIR:/system:ro" \
    -v "$SOURCE_PATH:/input/jemalloc-src.tar.bz2:ro" \
    -v "$OUTPUT_TEMP_PATH:/output/jemalloc-bin.tar.gz" \
    "${CACHE_PATH_MOUNT_ARGS[@]}" \
    -e "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" \
    -e "BUILD_CONCURRENCY=$BUILD_CONCURRENCY" \
    --user "$(id -u):$(id -g)" \
    "fullstaq/ruby-build-env-$ENVIRONMENT_NAME:$IMAGE_VERSION" \
    /system/container-entrypoints/build-jemalloc

function _cleanup() {
    echo '--- Exited Docker container ---'
    run mv "$OUTPUT_TEMP_PATH" "$OUTPUT_PATH"
}
