#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/lib/library.sh"

cd "$SELFDIR/environments"
for NAME in *; do
	IMAGE_VERSION=$(read_single_value_file "$NAME/image_tag")
	run docker push "fullstaq/ruby-build-env-$NAME:$IMAGE_VERSION"
done
