#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/lib/library.sh"

cd "$SELFDIR/environments"
for ENV in *; do
	IMAGE_VERSION=$(read_single_value_file "$ENV/image_tag")
	run docker push "ghcr.io/fullstaq-ruby/server-edition-ci-images:$ENV-v$IMAGE_VERSION"
done
