#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

JEMALLOC_DIR=/home/builder/jemalloc
RUBY_SRC_CONTAINER_DIR=/home/builder/ruby-src
DESTDIR=/home/builder/ruby-inst
INPUT_PATH=/input/ruby-src.tar.gz
JEMALLOC_BIN_TARBALL_PATH=/input/jemalloc-bin.tar.gz
OUTPUT_PATH=/output/ruby-bin.tar.gz

require_container_mount "$INPUT_PATH"
require_container_mount "$JEMALLOC_BIN_TARBALL_PATH"
require_container_mount "$OUTPUT_PATH"
require_container_envvar VERSION

BUILD_CONCURRENCY="${BUILD_CONCURRENCY:-4}"
INSTALL_PREFIX="/usr/lib/fullstaq-ruby/versions/$VERSION"


export C_INCLUDE_PATH="$JEMALLOC_DIR/include"
export CPLUS_INCLUDE_PATH="$JEMALLOC_DIR/include"
export LIBRARY_PATH="$JEMALLOC_DIR/lib"
export LD_LIBRARY_PATH="$JEMALLOC_DIR/lib"
export LD_RUN_PATH="$INSTALL_PREFIX/lib"


header "Setting up..."
if [[ -e /cache ]]; then
    echo "+ /cache is mounted in container, using it for ccache."
    export CCACHE_DIR=/cache/ccache
    export PATH="/usr/lib/ccache:$PATH"
    echo "+ Activating ccache compilers in /usr/lib/ccache."
    run mkdir -p "$CCACHE_DIR"
else
    echo "+ /cache is not mounted in the container, not using ccache."
fi
echo

header "Extracting Jemalloc binaries..."
run mkdir "$JEMALLOC_DIR"
run tar -xzf "$JEMALLOC_BIN_TARBALL_PATH" -C "$JEMALLOC_DIR"
echo

header "Extracting Ruby sources..."
run mkdir "$RUBY_SRC_CONTAINER_DIR"
run tar -xzf "$INPUT_PATH" -C "$RUBY_SRC_CONTAINER_DIR"

subdir="$(ls -1 "$RUBY_SRC_CONTAINER_DIR" | head -n 1)"
echo "+ cd $RUBY_SRC_CONTAINER_DIR/$subdir"
cd "$RUBY_SRC_CONTAINER_DIR/$subdir"
echo

header "Configuring and compiling Ruby..."
run ./configure --prefix="$INSTALL_PREFIX" \
    --enable-shared --disable-install-static-library \
    --with-jemalloc --disable-install-rdoc
run make "-j$BUILD_CONCURRENCY"
echo

header "Creating install directory structure..."
run make install DESTDIR="$DESTDIR"

run strip --strip-all "$DESTDIR/$INSTALL_PREFIX/bin/ruby"
echo "+ find $DESTDIR/$INSTALL_PREFIX -name '*.so' -print0 | xargs -0 strip --strip-debug"
set -o pipefail
find "$DESTDIR/$INSTALL_PREFIX" -name '*.so' -print0 | xargs -0 strip --strip-debug

run rm -rf "$DESTDIR/$INSTALL_PREFIX/share/man"
run mkdir -p "$DESTDIR/usr/lib/rbenv/versions"
run ln -s "$INSTALL_PREFIX" "$DESTDIR/usr/lib/rbenv/versions/$VERSION"

run cp -R "$JEMALLOC_DIR"/include/jemalloc "$DESTDIR/$INSTALL_PREFIX"/include/
run cp "$JEMALLOC_DIR"/lib/libjemalloc* "$DESTDIR/$INSTALL_PREFIX"/lib/

run tar -czf "$OUTPUT_PATH" -C "$DESTDIR" .
