#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

SRC_CONTAINER_DIR=/home/builder/jemalloc-src
INSTALL_PREFIX=/home/builder/jemalloc-inst
INPUT_PATH=/input/jemalloc-src.tar.bz2
OUTPUT_PATH=/output/jemalloc-bin.tar.gz

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"
require_container_envvar ENVIRONMENT_NAME

BUILD_CONCURRENCY="${BUILD_CONCURRENCY:-1}"


header "Setting up..."
if [[ -e /cache ]]; then
    echo "+ /cache is mounted in container, using it for ccache."
    export CCACHE_DIR=/cache/ccache
    export PATH="/usr/lib/ccache:$PATH"
    echo "+ Activating ccache compilers in /usr/lib/ccache."
    run mkdir -p "$CCACHE_DIR"
else
    echo "+ /cache is not mounted in the container, not using ccache."
fi
echo


header "Extracting Jemalloc tarball..."
run mkdir "$SRC_CONTAINER_DIR"
run tar -xjf "$INPUT_PATH" -C "$SRC_CONTAINER_DIR"

subdir="$(ls -1 "$SRC_CONTAINER_DIR" | head -n 1)"
echo "+ cd $SRC_CONTAINER_DIR/$subdir"
cd "$SRC_CONTAINER_DIR/$subdir"
echo


header "Compiling..."

# https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/issues/34
# https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/pull/32#issuecomment-554764548
echo "+ patch -p1 < /system/resources/jemalloc_cxx_fix.patch"
patch -t -p1 < /system/resources/jemalloc_cxx_fix.patch

run ./configure --prefix="$INSTALL_PREFIX" --enable-shared --disable-static
run make "-j$BUILD_CONCURRENCY"
run make install
run strip --strip-debug "$INSTALL_PREFIX/lib/libjemalloc.so"
run rm -rf "$INSTALL_PREFIX/lib/pkgconfig"

echo


header "Packaging up..."
echo "+ echo $ENVIRONMENT_NAME > $INSTALL_PREFIX/ENVIRONMENT"
echo "$ENVIRONMENT_NAME" > "$INSTALL_PREFIX/ENVIRONMENT"
run tar -czf "$OUTPUT_PATH" -C "$INSTALL_PREFIX" ENVIRONMENT include lib
