#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

WORK_DIR=/home/utility/work
INPUT_PATH=/input/ruby-bin.tar.gz
OUTPUT_PATH=/output/ruby.deb

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"
require_container_envvar REVISION


header "Extracting binaries..."
run mkdir "$WORK_DIR"
run tar -xzf "$INPUT_PATH" -C "$WORK_DIR"
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
ENVIRONMENT=$(cat ENVIRONMENT)
echo "+ Detected environment in which binaries were built: $ENVIRONMENT"
echo

header "Building package..."
echo "+ export BUNDLE_GEMFILE=/home/utility/Gemfile"
export BUNDLE_GEMFILE=/home/utility/Gemfile
DEPS=$(cat shlib-deps.txt)
PACKAGE_VERSION_WITH_SUFFIX=$(ls usr/lib/fullstaq-ruby/versions)
PACKAGE_VERSION_WITHOUT_SUFFIX=$(cat PACKAGE_VERSION)
VARIANT=$(cat VARIANT)
echo "+ Package version (with variant suffix) detected: $PACKAGE_VERSION_WITH_SUFFIX"
echo "+ Package version (without variant suffix) detected: $PACKAGE_VERSION_WITHOUT_SUFFIX"
echo "+ Variant detected: $VARIANT"
echo

set -x
# We embed metadata (variant and distro name) in the description field.
# This metadata is used by scripts such as internal-scripts/upload-deb.
bundle exec fpm -s dir -t deb -f --log info -C "$WORK_DIR" \
    --name "fullstaq-ruby-$PACKAGE_VERSION_WITH_SUFFIX" \
    --version "$REVISION" \
    --iteration "$ENVIRONMENT" \
    --license 'BSD 2-clause' \
    --vendor Fullstaq \
    --maintainer "Fullstaq <info@fullstaq.com>" \
    --description "Fullstaq Ruby $PACKAGE_VERSION_WITH_SUFFIX
Package version with variant suffix: $PACKAGE_VERSION_WITH_SUFFIX
Package version without variant suffix: $PACKAGE_VERSION_WITHOUT_SUFFIX
Variant: $VARIANT
Distribution: $ENVIRONMENT" \
    --url "https://github.com/fullstaq-ruby/server-edition" \
    --depends "$DEPS" \
    --provides fullstaq-ruby \
    --deb-recommends fullstaq-ruby-common \
    --deb-dist "$ENVIRONMENT" \
    usr
set +x
run cp *.deb "$OUTPUT_PATH"
