#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

WORK_DIR=/home/utility/work
INPUT_PATH=/input/ruby-bin.tar.gz
OUTPUT_PATH=/output/ruby.deb

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"
require_container_envvar REVISION
require_container_envvar DISTRO


header "Extracting binaries..."
run mkdir "$WORK_DIR"
run tar -xzf "$INPUT_PATH" -C "$WORK_DIR"
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
echo

header "Building package..."
echo "+ export BUNDLE_GEMFILE=/home/utility/Gemfile"
export BUNDLE_GEMFILE=/home/utility/Gemfile
DEPS=$(cat shlib-deps.txt)
VERSION=$(ls usr/lib/fullstaq-ruby/versions)

set -x
bundle exec fpm -s dir -t deb -f --log info -C "$WORK_DIR" \
    --name "fullstaq-ruby-$VERSION" \
    --version "$REVISION" \
    --iteration "$DISTRO" \
    --license MIT \
    --vendor Fullstaq \
    --maintainer "Fullstaq <info@fullstaq.com>" \
    --description "Fullstaq Ruby $VERSION" \
    --url "https://github.com/fullstaq-labs/fullstaq-ruby-server-edition" \
    --depends "$DEPS" \
    --provides fullstaq-ruby \
    --deb-recommends fullstaq-rbenv \
    --deb-dist "$DISTRO" \
    usr
set +x
run cp *.deb "$OUTPUT_PATH"
