#!/bin/bash
set -e

# If you make a change that changes the RPM's contents or metadata,
# then be sure to bump `common.rpm.version` or
# `common.rpm.package_revision` in config.yml.

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

WORK_DIR=/home/utility/work
OUTPUT_PATH=/output/common.rpm

require_container_mount "$OUTPUT_PATH"
require_container_envvar VERSION
require_container_envvar REVISION


header "Building package..."
run mkdir "$WORK_DIR"
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
echo "+ export BUNDLE_GEMFILE=/home/utility/Gemfile"
export BUNDLE_GEMFILE=/home/utility/Gemfile

set -x
bundle exec fpm -s dir -t rpm -f --log info \
    --name "fullstaq-ruby-common" \
    --version "$VERSION" \
    --iteration "$REVISION" \
    --architecture all \
    --license MIT \
    --vendor Fullstaq \
    --maintainer "Fullstaq <info@fullstaq.com>" \
    --description "Fullstaq Ruby common dependencies" \
    --url "https://github.com/fullstaq-ruby/server-edition" \
    --depends "fullstaq-rbenv" \
    .
set +x
run cp *.rpm "$OUTPUT_PATH"
