#!/bin/bash
set -e

# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

JEMALLOC_DIR=/home/builder/jemalloc
RUBY_SRC_CONTAINER_DIR=/home/builder/ruby-src
DESTDIR=/home/builder/ruby-inst

require_container_mount /input
require_container_mount /output
require_container_envvar VERSION
require_container_envvar JEMALLOC_BIN_TARBALL_NAME

RUBY_TARBALL_NAME="${RUBY_TARBALL_NAME:-ruby-"$VERSION".tar.gz}"
RUBY_TARBALL_PATH="/input/$RUBY_TARBALL_NAME"
JEMALLOC_BIN_TARBALL_PATH="/input/$JEMALLOC_BIN_TARBALL_NAME"
OUTPUT_NAME="${OUTPUT_NAME:-ruby-bin-"$VERSION".tar.gz}"
OUTPUT_PATH="/output/$OUTPUT_NAME"
BUILD_CONCURRENCY="${BUILD_CONCURRENCY:-4}"
INSTALL_PREFIX="/usr/lib/fullstaq-ruby/versions/$VERSION"


export C_INCLUDE_PATH="$JEMALLOC_DIR/include"
export CPLUS_INCLUDE_PATH="$JEMALLOC_DIR/include"
export LIBRARY_PATH="$JEMALLOC_DIR/lib"
export LD_LIBRARY_PATH="$JEMALLOC_DIR/lib"
export LD_RUN_PATH="$INSTALL_PREFIX/lib"


header "Setting up..."
if [[ -e /cache ]]; then
    echo "+ /cache is mounted in container, using it for ccache."
    export CCACHE_PATH=/cache/ccache
    export PATH="/usr/lib/ccache:$PATH"
    echo "+ Activating ccache compilers in /usr/lib/ccache."
    run mkdir -p "$CCACHE_PATH"
else
    echo "+ /cache is not mounted in the container, not using ccache."
fi

header "Extracting Jemalloc binaries..."
run mkdir "$JEMALLOC_DIR"
run tar -xzf "$JEMALLOC_BIN_TARBALL_PATH" -C "$JEMALLOC_DIR"

run mkdir "$RUBY_SRC_CONTAINER_DIR"
run tar -xzf "$RUBY_TARBALL_PATH" -C "$RUBY_SRC_CONTAINER_DIR"

subdir="$(ls -1 "$RUBY_SRC_CONTAINER_DIR" | head -n 1)"
echo "+ cd $RUBY_SRC_CONTAINER_DIR/$subdir"
cd "$RUBY_SRC_CONTAINER_DIR/$subdir"

run ./configure --INSTALL_prefix="$INSTALL_PREFIX" \
    --enable-shared --disable-install-static-library \
    --with-jemalloc --disable-install-rdoc
run make "-j$BUILD_CONCURRENCY"
run make install DESTDIR="$DESTDIR"
run strip --strip-all "$DESTDIR/$INSTALL_PREFIX/bin/ruby"
echo "+ find $DESTDIR/$INSTALL_PREFIX -name '*.so' -print0 | xargs -0 strip --strip-debug"
set -o pipefail
find "$DESTDIR/$INSTALL_PREFIX" -name '*.so' -print0 | xargs -0 strip --strip-debug
run rm -rf "$DESTDIR/$INSTALL_PREFIX/share/man"

run cp -R "$JEMALLOC_DIR"/include/jemalloc "$DESTDIR/$INSTALL_PREFIX"/include/
run cp "$JEMALLOC_DIR"/lib/libjemalloc* "$DESTDIR/$INSTALL_PREFIX"/lib/

run tar -czf "$OUTPUT_PATH" -C "$DESTDIR" .
