#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

WORK_DIR=/home/utility/work
INPUT_PATH=/input/ruby-bin.tar.gz
OUTPUT_PATH=/output/ruby.deb

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"


header "Extracting binaries..."
run mkdir "$WORK_DIR"
run tar -xzf "$INPUT_PATH" -C "$WORK_DIR"
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
echo

header "Building package..."
echo "+ export BUNDLE_GEMFILE=/home/utility/Gemfile"
export BUNDLE_GEMFILE=/home/utility/Gemfile
run bundle exec fpm -s dir -t deb -f \
	-C "$WORK_DIR" \
	-n ruby \
	-p ruby.deb \
	-d "$(cat shlib-deps.txt)" \
	usr
run cp ruby.deb "$OUTPUT_PATH"
