#!/bin/bash
set -e

# If you make a change that changes the DEB's contents or metadata,
# then be sure to bump `rbenv.package_revision` in config.yml.

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

WORK_DIR=/home/utility/work
INPUT_PATH=/input/rbenv
OUTPUT_PATH=/output/rbenv.deb

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"
require_container_envvar VERSION
require_container_envvar REVISION


header "Preparing input..."
run mkdir "$WORK_DIR"
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
run cp -dpR "$INPUT_PATH"/{bin,completions,libexec,rbenv.d} ./
run mkdir system
run mkdir system/bin
run ln -s /usr/lib/rbenv/libexec/rbenv system/bin/rbenv
echo

header "Building package..."
echo "+ cd $WORK_DIR"
cd "$WORK_DIR"
echo "+ export BUNDLE_GEMFILE=/home/utility/Gemfile"
export BUNDLE_GEMFILE=/home/utility/Gemfile

set -x
bundle exec fpm -s dir -t deb -f --log info \
    --name "fullstaq-rbenv" \
    --version "$VERSION" \
    --iteration "$REVISION" \
    --architecture all \
    --license MIT \
    --vendor Fullstaq \
    --maintainer "Fullstaq <info@fullstaq.com>" \
    --description "Fullstaq Rbenv $VERSION" \
    --url "https://github.com/fullstaq-labs/fullstaq-rbenv" \
    --provides rbenv \
    system/bin=/usr/ \
    bin=/usr/lib/rbenv/ \
    libexec=/usr/lib/rbenv/ \
    rbenv.d=/usr/lib/rbenv/ \
    completions=/usr/lib/rbenv/
set +x
run cp *.deb "$OUTPUT_PATH"
