#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

INPUT_PATH=/input
OUTPUT_PATH=/output

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"


run aptly repo create test
run aptly repo add test /input/*.deb
run aptly publish repo -skip-signing -distribution=test test
run cp -dpR ~/.aptly/public/* "$OUTPUT_PATH/"
