#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

export REPO_PATH=/input/repo

require_container_mount "$REPO_PATH"
require_container_envvar EXPECTED_VARIANT
if [[ "$SERVER" != "" ]]; then
    require_container_envvar RUBY_PACKAGE_VERSION
fi
require_container_envvar DEBUG_ON_FAIL

if ! /system/internal-scripts/test-rpms; then
    echo
    echo '-------------------'
    if $DEBUG_ON_FAIL; then
        if tty -s; then
            echo '*** ERROR: Test run failed. Opening a shell session for debugging.'
            echo '    TIP: run this to activate Rbenv: eval "$(rbenv init -)"'
            bash -l
        else
            echo '*** ERROR: Test run failed. Cannot open a debug shell session either because there is no TTY.'
        fi
    else
        echo '*** ERROR: Test run failed. If you passed -D then a debug shell session would have been opened.'
    fi
    exit 1
fi
