#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"

INPUT_PATH=/input
OUTPUT_PATH=/output

require_container_mount "$INPUT_PATH"
require_container_mount "$OUTPUT_PATH"


run cp /input/* /output/
run createrepo /output
