#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"


header "Installing packages"
if ls -d /input/repo/pool/main/f/*jemalloc 2>/dev/null; then
    VARIANT=jemalloc
    VARIANT_VERSION_SUFFIX=-jemalloc
elif ls -d /input/repo/pool/main/f/*malloctrim 2>/dev/null; then
    VARIANT=malloctrim
    VARIANT_VERSION_SUFFIX=-malloctrim
else
    VARIANT=normal
    VARIANT_VERSION_SUFFIX=
fi
echo "+ Detected variant: $VARIANT"
echo "+ Create /etc/yum.repos.d/local.repo"
cat <<EOF > /etc/yum.repos.d/local.repo
[local]
name=local
baseurl=file:///input/repo
gpgcheck=0
EOF
run yum install -y "fullstaq-ruby-$RUBY_PACKAGE_VERSION" fullstaq-rbenv sudo which
echo


header "Setting up"
groupadd --gid 9999 utility
adduser --uid 9999 --gid 9999 --password '#' utility
echo "+ Loading Rbenv environment"
eval "$(rbenv init -)"
run rbenv global "$RUBY_PACKAGE_VERSION"
run sudo -u utility -H rbenv global "$RUBY_PACKAGE_VERSION"
echo


header "Basic checks"

function assert_equals()
{
    local real="$1"
    local expected="$2"
    if [[ "$real" == "$expected" ]]; then
        echo yes
    else
        echo no
        echo "  Expected: $expected"
        echo "  Actual  : $real"
        return 1
    fi
}

echo -n "Checking whether variant is $EXPECTED_VARIANT... "
assert_equals "$VARIANT" "$EXPECTED_VARIANT"

echo -n "Checking whether Rbenv is in /usr/bin/rbenv... "
output=$(which rbenv)
assert_equals "$output" /usr/bin/rbenv

echo -n "Checking whether Fullstaq Ruby $RUBY_PACKAGE_VERSION is in /usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX... "
if [[ -e "/usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX/bin/ruby" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether active Ruby for root is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX/bin/ruby... "
output=$(rbenv which ruby)
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX/bin/ruby"

echo -n "Checking whether active Ruby for utility is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX/bin/ruby... "
output=$(sudo -u utility -H sh -c 'eval "$(rbenv init -)" && rbenv which ruby')
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION$VARIANT_VERSION_SUFFIX/bin/ruby"

echo -n "Checking whether Ruby works... "
output=$(ruby -e 'puts "hello world"')
assert_equals "$output" "hello world"

echo -n "Checking whether Ruby native libraries work... "
output=$(ruby -rbigdecimal -e "puts BigDecimal.new(0)")
assert_equals "$output" "0.0"

echo -n "Checking whether irb works... "
output=$(irb <<<'puts "hello world"')
if [[ "$output" =~ "hello world" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether gem works... "
output=$(gem env)
if grep -Fq "RUBY VERSION: $RUBY_PACKAGE_VERSION" <<<"$output"; then
    echo yes
else
    echo no
    exit 1
fi

echo


header "Test installing gems"
run yum install -y gcc gcc-c++ make
run gem install bundler -v 1.17.3 --no-document
run sudo -u utility -H cp /system/resources/test-env/Gemfile* ~utility/
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle install --path=/home/utility/bundle -j 4
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle exec rspec --version

echo
echo "All tests pass."
