#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"


header "Installing packages"
run yum install -y perl sudo binutils which

if [[ "$SERVER" = "" ]]; then
    RPM_INFO=$(rpm -qpi /input/repo/fullstaq-ruby-*.rpm)
    RUBY_PACKAGE_VERSION=$(grep '^Package version with variant suffix:' <<<"$RPM_INFO" | perl -pe 's/.*?: *//')
    RUBY_PACKAGE_VERSION_WITHOUT_VARIANT_SUFFIX=$(grep '^Package version without variant suffix:' <<<"$RPM_INFO" | perl -pe 's/.*?: *//')
    VARIANT=$(grep '^Variant:' <<<"$RPM_INFO" | perl -pe 's/.*?: *//')

    echo "+ Create /etc/yum.repos.d/local.repo"
    cat <<EOF > /etc/yum.repos.d/local.repo
[local]
name=local
baseurl=file:///input/repo
gpgcheck=0
enabled=1
EOF
else
    echo "+ Create /etc/yum.repos.d/fullstaq-ruby.repo"
    cat <<EOF > /etc/yum.repos.d/fullstaq-ruby.repo
[fullstaq-ruby]
name=fullstaq-ruby
baseurl=$SERVER/\$basearch
gpgcheck=0
repo_gpgcheck=1
enabled=1
gpgkey=file:///system/fullstaq-ruby.asc
sslverify=1
EOF
    run yum -q makecache -y --disablerepo='*' --enablerepo=fullstaq-ruby
    RPM_INFO=$(yum info "fullstaq-ruby-$RUBY_PACKAGE_VERSION")
    RUBY_PACKAGE_VERSION_WITHOUT_VARIANT_SUFFIX=$(grep 'Package version without variant suffix:' <<<"$RPM_INFO" | perl -pe 's/ *:.*?: *//')
    VARIANT=$(grep 'Variant:' <<<"$RPM_INFO" | perl -pe 's/ *:.*?: *//')
fi

echo "+ Detected package version (possibly with variant suffix): $RUBY_PACKAGE_VERSION"
echo "+ Detected package version (without variant suffix): $RUBY_PACKAGE_VERSION_WITHOUT_VARIANT_SUFFIX"
echo "+ Detected variant: $VARIANT"

if [[ "$SERVER" = "" ]]; then
    run yum install -y "fullstaq-ruby-$RUBY_PACKAGE_VERSION" fullstaq-ruby-common
else
    # Bintray could sometimes be flaky, so we retry on failure.
    run_with_retries yum install -y "fullstaq-ruby-$RUBY_PACKAGE_VERSION" fullstaq-ruby-common
fi

echo


header "Setting up"
groupadd --gid 9999 utility
adduser --uid 9999 --gid 9999 --password '#' utility
echo "+ Loading Rbenv environment"
eval "$(rbenv init -)"
run rbenv global "$RUBY_PACKAGE_VERSION"
run sudo -u utility -H rbenv global "$RUBY_PACKAGE_VERSION"
echo


header "Basic checks"

function assert_equals()
{
    local real="$1"
    local expected="$2"
    if [[ "$real" == "$expected" ]]; then
        echo yes
    else
        echo no
        echo "  Expected: $expected"
        echo "  Actual  : $real"
        return 1
    fi
}

echo -n "Checking whether variant is $EXPECTED_VARIANT... "
assert_equals "$VARIANT" "$EXPECTED_VARIANT"

echo -n "Checking whether Rbenv is in /usr/bin/rbenv... "
output=$(which rbenv)
assert_equals "$output" /usr/bin/rbenv

echo -n "Checking whether Fullstaq Ruby $RUBY_PACKAGE_VERSION is in /usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION... "
if [[ -e "/usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION/bin/ruby" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether active Ruby for root is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby... "
output=$(rbenv which ruby)
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby"

echo -n "Checking whether the package version contains the proper variant suffix... "
if [[ "$VARIANT" = normal ]]; then
    if [[ ! "$RUBY_PACKAGE_VERSION" =~ - ]]; then
        echo yes
    else
        echo no
        echo "  '$RUBY_PACKAGE_VERSION' contains a dash, so it is presumed to contain a variant suffix."
        exit 1
    fi
elif [[ "$VARIANT" = jemalloc ]]; then
    if [[ "$RUBY_PACKAGE_VERSION" =~ -jemalloc$ ]]; then
        echo yes
    else
        echo no
        echo "  Expected '$RUBY_PACKAGE_VERSION' to end with '-jemalloc'."
        exit 1
    fi
elif [[ "$VARIANT" = malloctrim ]]; then
    if [[ "$RUBY_PACKAGE_VERSION" =~ -malloctrim$ ]]; then
        echo yes
    else
        echo no
        echo "  Expected '$RUBY_PACKAGE_VERSION' to end with '-malloctrim'."
        exit 1
    fi
else
    echo "BUG: unsupported variant $VARIANT" >&2
    exit 1
fi

echo -n "Checking whether active Ruby for utility is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby... "
output=$(sudo -u utility -H bash -c 'eval "$(rbenv init -)" && rbenv which ruby')
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby"

echo -n "Checking whether Ruby works... "
output=$(ruby -e 'puts "hello world"')
assert_equals "$output" "hello world"

echo -n "Checking whether Ruby native libraries work... "
output=$(ruby -rbigdecimal -e "puts BigDecimal(0)")
assert_equals "$output" "0.0"

echo -n "Checking whether irb works... "
output=$(irb <<<'puts "hello world"')
if [[ "$output" =~ "hello world" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether gem works... "
output=$(gem env)
if grep -Fq "RUBY VERSION: $RUBY_PACKAGE_VERSION_WITHOUT_VARIANT_SUFFIX" <<<"$output"; then
    echo yes
else
    echo no
    echo "  Expected 'gem env' output to contain 'RUBY VERSION: $RUBY_PACKAGE_VERSION_WITHOUT_VARIANT_SUFFIX'"
    exit 1
fi

if [[ "$VARIANT" = jemalloc ]]; then
    echo -n "Checking whether Jemalloc library exists... "
    if [[ -e "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib/libjemalloc.so" ]]; then
        echo yes
    else
        echo no
        exit 1
    fi

    echo -n "Checking whether Ruby is linked to Jemalloc... "
    output=$(objdump -p "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib/libruby.so")
    if grep NEEDED <<<"$output" | grep -q libjemalloc.so; then
        echo yes
    else
        echo no
        exit 1
    fi

    echo -n "Checking whether 'ruby -v' mentions Jemalloc... "
    output=$(ruby -v)
    if grep -qF '+jemalloc' <<<"$output"; then
        echo yes
    else
        echo no
        exit 1
    fi

    echo -n "Checking whether jemalloc.so is a symlink... "
    if [[ -h "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib/libjemalloc.so" ]]; then
        echo yes
    else
        echo no
        exit 1
    fi
else
    echo -n "Checking whether Jemalloc library does not exist... "
    if [[ ! -e "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib/libjemalloc.so" ]]; then
        echo yes
    else
        echo no
        exit 1
    fi

    echo -n "Checking whether Ruby is not linked to Jemalloc... "
    output=$(objdump -p "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib/libruby.so")
    if ! grep NEEDED <<<"$output" | grep -q libjemalloc.so; then
        echo yes
    else
        echo no
        exit 1
    fi

    if [[ "$VARIANT" = malloctrim ]]; then
        echo -n "Checking whether 'ruby -v' mentions malloctrim... "
        output=$(ruby -v)
        if grep -qF '+malloctrim' <<<"$output"; then
            echo yes
        else
            echo no
            exit 1
        fi
    fi
fi

echo -n "Checking whether package contains no static libraries... "
shopt -s nullglob
static_libs=("/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/lib"/*.a)
shopt -u nullglob
if [[ "${#static_libs[@]}" -eq 0 ]]; then
    echo ok
else
    echo error
    echo "The following static libraries were found:"
    for F in "${static_libs[@]}"; do
        echo " - $F"
    done
    exit 1
fi

echo


header "Test installing gems"
run yum install -y gcc gcc-c++ make
run gem install bundler -v 2.1.4 --no-document
run sudo -u utility -H cp /system/resources/test-env/Gemfile* ~utility/
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle install --path=/home/utility/bundle -j 4
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle exec rspec --version
echo


if [[ "$VARIANT" = jemalloc ]]; then
    # https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/issues/34
    # https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/pull/32#issuecomment-554764548
    header "Test Jemalloc C++ compatibility"
    INCLUDE_DIR=$(ruby -rrbconfig -e 'puts RbConfig::CONFIG["rubyhdrdir"]')
    run c++ "-I$INCLUDE_DIR" -Wall /system/resources/test-env/jemalloc-cxx.cpp -o /tmp/jemalloc_cxx
fi


echo
echo "All tests pass."
