#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=../lib/library.sh
source "$SELFDIR/../lib/library.sh"

function list_rpm_environments()
{
    grep -lE '(yum|dnf) install' /system/environments/*/Dockerfile |
        xargs -n 1 dirname |
        xargs -n 1 basename |
        grep -v utility
}

function upload()
{
    local REPO_DISTRO="$1"
    local REPO_ARCH="$2"
    local REPO_OVERRIDE="$3"
    local -a CURL_COMMAND=(
        curl -sSLf --netrc-file /tmp/curl-creds -X PUT -T "$FILE"
        "https://api.bintray.com/api/v1/content/fullstaq/$REPO_NAME/fullstaq-ruby/all/$REPO_DISTRO/$REPO_ARCH/$BASENAME?override=$REPO_OVERRIDE"
    )
    if $DRY_RUN; then
        echo "+ Dry-running: ${CURL_COMMAND[*]}"
    else
        set +e
        run "${CURL_COMMAND[@]}" 2>&1
        local EXITSTATUS=$?
        set -e

        # Ensure that the output ends with a newline even if the HTTP response doesn't.
        echo
        return "$EXITSTATUS"
    fi
}

REPO_NAME="$1"
FILE="$2"
BASENAME="$3"
REPUBLISH="$4"

ALL_SUPPORTED_DISTROS=($(list_rpm_environments))
ALL_SUPPORTED_ARCHITECTURES=(x86_64)

set -o pipefail

RPM_INFO=$(rpm -qpi "$FILE")

ARCHS=($(grep '^Architecture *:' <<<"$RPM_INFO" | perl -pe 's/.*?: *//'))
if [[ "${ARCHS[0]}" = noarch ]]; then
    ARCHS=("${ALL_SUPPORTED_ARCHITECTURES[@]}")
fi

if grep -q '^Distribution:' <<<"$RPM_INFO"; then
    DISTROS=($(grep '^Distribution:' <<<"$RPM_INFO" | perl -pe 's/.*?: *//'))
else
    DISTROS=("${ALL_SUPPORTED_DISTROS[@]}")
fi

if $REPUBLISH; then
    OVERRIDE=1
else
    OVERRIDE=0
fi

for REPO_DISTRO in "${DISTROS[@]}"; do
    for REPO_ARCH in "${ARCHS[@]}"; do
        upload "$REPO_DISTRO" "$REPO_ARCH" "$OVERRIDE"
    done
done
