#!/bin/bash
set -e

SELFDIR=$(dirname "$0")
SELFDIR=$(cd "$SELFDIR" && pwd)
# shellcheck source=lib/library.sh
source "$SELFDIR/../lib/library.sh"


header "Installing packages"
echo "+ Create /etc/apt/sources.list.d/local.list"
echo "deb [allow-insecure=yes] file:$REPO_PATH test main" > /etc/apt/sources.list.d/local.list
cat /etc/apt/sources.list.d/local.list
run apt update
run apt install -y --allow-unauthenticated "fullstaq-ruby-$RUBY_PACKAGE_VERSION" sudo
echo


header "Setting up"
run addgroup --gid 9999 utility
run adduser --uid 9999 --gid 9999 --disabled-password --gecos Utility utility
run usermod -L utility
echo "+ Loading Rbenv environment"
eval "$(rbenv init -)"
run rbenv global "$RUBY_PACKAGE_VERSION"
run sudo -u utility -H rbenv global "$RUBY_PACKAGE_VERSION"
echo


header "Basic sanity checks"

function assert_equals()
{
    local real="$1"
    local expected="$2"
    if [[ "$real" == "$expected" ]]; then
        echo yes
    else
        echo no
        echo "  Expected: $expected"
        echo "  Actual  : $real"
        return 1
    fi
}

echo -n "Checking whether Rbenv is in /usr/bin/rbenv... "
output=$(which rbenv)
assert_equals "$output" /usr/bin/rbenv

echo -n "Checking whether Fullstaq Ruby $RUBY_PACKAGE_VERSION is in /usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION... "
if [[ -e "/usr/lib/fullstaq-ruby/versions/$RUBY_PACKAGE_VERSION/bin/ruby" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether active Ruby for root is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby... "
output=$(rbenv which ruby)
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby"

echo -n "Checking whether active Ruby for utility is /usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby... "
output=$(sudo -u utility -H sh -c 'eval "$(rbenv init -)" && rbenv which ruby')
assert_equals "$output" "/usr/lib/rbenv/versions/$RUBY_PACKAGE_VERSION/bin/ruby"

echo -n "Checking whether Ruby works... "
output=$(ruby -e 'puts "hello world"')
assert_equals "$output" "hello world"

echo -n "Checking whether Ruby native libraries work... "
output=$(ruby -rbigdecimal -e "puts BigDecimal.new(0)")
assert_equals "$output" "0.0"

echo -n "Checking whether irb works... "
output=$(irb <<<'puts "hello world"')
if [[ "$output" =~ "hello world" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo -n "Checking whether gem works... "
output=$(gem env)
if [[ "$output" =~ "RUBY VERSION: $RUBY_PACKAGE_VERSION" ]]; then
    echo yes
else
    echo no
    exit 1
fi

echo


header "Test installing gems"
run apt install -y build-essential
run gem install bundler -v 1.17.3 --no-document
run sudo -u utility -H cp /system/resources/test-env/Gemfile* ~utility/
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle install --path=/home/utility/bundle -j 4
run sudo -u utility -H env BUNDLE_GEMFILE=/home/utility/Gemfile \
    rbenv exec bundle exec rspec --version

echo
echo "All tests pass."
