#!/bin/bash
set -e
set -o pipefail

SELFDIR=$(dirname "$0")
ROOTDIR=$(cd "$SELFDIR/../../.." && pwd)


# shellcheck disable=SC2207
AUTOGENERATED_WORKFLOW_NAMES=($(
    find "$ROOTDIR"/.github/workflows/*.yml.erb -print0 | \
    xargs -0 -n 1 basename | \
    sed -e 's|.*/||; s|\.yml\.erb$||'
))

for WORKFLOW_NAME in "${AUTOGENERATED_WORKFLOW_NAMES[@]}"; do
    cp "$ROOTDIR/.github/workflows/$WORKFLOW_NAME.yml" "$ROOTDIR/.github/workflows/$WORKFLOW_NAME.yml.old"
done

"$ROOTDIR"/internal-scripts/generate-ci-cd-yaml.rb

for WORKFLOW_NAME in "${AUTOGENERATED_WORKFLOW_NAMES[@]}"; do
    CHECKSUM_A=$(md5sum .github/workflows/"$WORKFLOW_NAME".yml.old | awk '{ print $1 }')
    CHECKSUM_B=$(md5sum .github/workflows/"$WORKFLOW_NAME".yml | awk '{ print $1 }')
    if [[ "$CHECKSUM_A" = "$CHECKSUM_B" ]]; then
        echo "$WORKFLOW_NAME"': up-to-date!'
    else
        echo "ERROR: .github/workflows/$WORKFLOW_NAME.yml is not up-to-date"'!'
        echo 'Please run this script, then commit and push:'
        echo
        echo '  ./internal-scripts/generate-ci-cd-yaml.rb'
        echo
        echo 'TIP: run this on your development machine to ensure generate-ci-cd-yaml.rb is run automatically as a Git pre-commit hook:'
        echo
        echo '  git config core.hooksPath .githooks'
        echo
        echo "Here's the difference:"
        git diff --no-index --color .github/workflows/"$WORKFLOW_NAME".yml.old .github/workflows/"$WORKFLOW_NAME".yml
        exit 1
    fi
done
