# This Gemfile will be installed into the test container
# when running a test suite.
source 'https://rubygems.org'

# Must allow for the minimum Ruby version that we support in config.yml.
ruby '>= 3.1'

# Test engine to use
gem 'rspec'

# Tests whether installing native extensions works
gem 'bcrypt'
